-- =========================================================================
-- LazySwindle Default Configuration
-- =========================================================================
-- This is the core configuration file for the Swindle compositor.
-- It is written in Lua and loaded dynamically at runtime.
-- Changes to this file (or the theme file it includes) will be hot-reloaded
-- instantly by the compositor without needing a restart!
-- =========================================================================

-- -------------------------------------------------------------------------
-- THEME INTEGRATION
-- -------------------------------------------------------------------------
-- We dynamically load the theme generated by the LazySwindle AGS Shell.
-- This allows the Settings App to control gaps, borders, and colors on the fly!
local theme = {}
pcall(function() theme = dofile(os.getenv("HOME") .. "/.config/swindle/lazyswindle_theme.lua") end)

-- -------------------------------------------------------------------------
-- APPEARANCE
-- -------------------------------------------------------------------------
-- Controls the visual layout of windows. Colors are defined as {R, G, B, Alpha}
-- from 0.0 to 1.0. These default to the generated AGS theme.
appearance = {
    gaps = theme.gaps or 10,                            -- Space between windows (in pixels)
    smart_gaps = false,                                 -- If true, disables gaps when only one window is open
    border_px = theme.border_px or 2,                   -- Window border thickness (in pixels)
    border_color = theme.border_color or {0.08, 0.08, 0.11, 1.0}, -- Border color of inactive windows
    focus_color = theme.focus_color or {0.47, 0.63, 0.96, 1.0},   -- Border color of the active window
    urgent_color = theme.urgent_color or {0.96, 0.46, 0.55, 1.0}, -- Border color of windows requesting attention
    root_color = theme.root_color or {0.10, 0.10, 0.14, 1.0},     -- Desktop background color (if no wallpaper is set)
    fullscreen_bg = {0.0, 0.0, 0.0, 1.0},               -- Background color behind fullscreen apps
}

-- -------------------------------------------------------------------------
-- MONITORS
-- -------------------------------------------------------------------------
-- Configure multi-monitor setups and their default layouts here.
-- Leaving name as "" matches all available monitors.
monitors = {
    { name = "", layout = "dwindle" } -- Default layout algorithm is "dwindle"
}

-- -------------------------------------------------------------------------
-- INPUT DEVICES
-- -------------------------------------------------------------------------
-- Touchpad, mouse, and keyboard global settings.
input = {
    natural_scrolling = false, -- Invert scrolling direction (Mac-style)
    tap_to_click = true,       -- Allow tapping touchpad to click
}

-- -------------------------------------------------------------------------
-- AUTOSTART
-- -------------------------------------------------------------------------
-- Commands to run automatically when Swindle starts.
-- We must start the 'ags' shell here!
autostart = {
    "sh -c 'ags -c ~/.config/ags/main.ts'"
}

-- -------------------------------------------------------------------------
-- WINDOW RULES (FLOATING MODE)
-- -------------------------------------------------------------------------
-- Define rules to force specific applications to open in floating mode
-- or launch on specific workspaces (tags).
-- Leaving app_id or title blank ("") matches everything.
rules = {
    -- Example: Force the calculator to always open floating
    { app_id = "org.gnome.Calculator", title = "", floating = true, tags = 0 },
    -- Example: Force pavucontrol to float
    { app_id = "pavucontrol", title = "", floating = true, tags = 0 },
}

-- -------------------------------------------------------------------------
-- KEYBINDINGS
-- -------------------------------------------------------------------------
-- Define your keyboard shortcuts here.
-- Common Modifiers: 
-- "logo" = Super/Windows key
-- "alt" = Alt key
-- "shift", "ctrl"
-- -------------------------------------------------------------------------
keybinds = {
    -- Application Launchers
    { mods = {"logo"}, key = "t", action = "spawn", args = {"ghostty"} },
    { mods = {"logo"}, key = "d", action = "spawn", args = {"sh", "-c", "ags -c ~/.config/ags/main.ts -t launcher"} },
    { mods = {"logo"}, key = "Space", action = "spawn", args = {"sh", "-c", "ags -c ~/.config/ags/main.ts -t settings"} },
    { mods = {"logo"}, key = "Comma", action = "spawn", args = {"sh", "-c", "ags -c ~/.config/ags/main.ts -t settings"} },

    -- Window Management
    { mods = {"logo"}, key = "q", action = "killclient" },
    { mods = {"logo", "shift"}, key = "t", action = "togglefloating" },
    { mods = {"logo", "shift"}, key = "f", action = "togglefullscreen" },

    -- Niri-style Directional Focus (Switching Windows)
    { mods = {"logo"}, key = "Left", action = "focusdir", args = {"left"} },
    { mods = {"logo"}, key = "Right", action = "focusdir", args = {"right"} },
    { mods = {"logo"}, key = "Up", action = "focusdir", args = {"up"} },
    { mods = {"logo"}, key = "Down", action = "focusdir", args = {"down"} },

    -- Niri-style Directional Movement (Moving Windows)
    { mods = {"logo", "shift"}, key = "Left", action = "swapdir", args = {"left"} },
    { mods = {"logo", "shift"}, key = "Right", action = "swapdir", args = {"right"} },
    { mods = {"logo", "shift"}, key = "Up", action = "swapdir", args = {"up"} },
    { mods = {"logo", "shift"}, key = "Down", action = "swapdir", args = {"down"} },

    -- Workspace Switching (1-9, bitmask: 1<<(n-1))
    { mods = {"logo"}, key = "1", action = "view", args = {"1"} },
    { mods = {"logo"}, key = "2", action = "view", args = {"2"} },
    { mods = {"logo"}, key = "3", action = "view", args = {"4"} },
    { mods = {"logo"}, key = "4", action = "view", args = {"8"} },
    { mods = {"logo"}, key = "5", action = "view", args = {"16"} },
    { mods = {"logo"}, key = "6", action = "view", args = {"32"} },
    { mods = {"logo"}, key = "7", action = "view", args = {"64"} },
    { mods = {"logo"}, key = "8", action = "view", args = {"128"} },
    { mods = {"logo"}, key = "9", action = "view", args = {"256"} },

    -- Move Window to Workspace (1-9, bitmask: 1<<(n-1))
    { mods = {"logo", "shift"}, key = "1", action = "tag", args = {"1"} },
    { mods = {"logo", "shift"}, key = "2", action = "tag", args = {"2"} },
    { mods = {"logo", "shift"}, key = "3", action = "tag", args = {"4"} },
    { mods = {"logo", "shift"}, key = "4", action = "tag", args = {"8"} },
    { mods = {"logo", "shift"}, key = "5", action = "tag", args = {"16"} },
    { mods = {"logo", "shift"}, key = "6", action = "tag", args = {"32"} },
    { mods = {"logo", "shift"}, key = "7", action = "tag", args = {"64"} },
    { mods = {"logo", "shift"}, key = "8", action = "tag", args = {"128"} },
    { mods = {"logo", "shift"}, key = "9", action = "tag", args = {"256"} },

    -- System Controls
    { mods = {"logo", "shift"}, key = "e", action = "quit" },

    -- Screenshots
    { mods = {}, key = "Print", action = "spawn", args = {"sh", "-c", 'mkdir -p ~/Pictures && grim -g "$(slurp)" ~/Pictures/screenshot_$(date +%s).png'} },
    { mods = {"shift"}, key = "Print", action = "spawn", args = {"sh", "-c", 'mkdir -p ~/Pictures && grim ~/Pictures/screenshot_$(date +%s).png'} },

    -- Media & Brightness Controls
    { mods = {}, key = "XF86AudioRaiseVolume", action = "spawn", args = {"wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%+"} },
    { mods = {}, key = "XF86AudioLowerVolume", action = "spawn", args = {"wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-"} },
    { mods = {}, key = "XF86AudioMute", action = "spawn", args = {"wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle"} },
    { mods = {}, key = "XF86MonBrightnessUp", action = "spawn", args = {"brightnessctl", "s", "5%+"} },
    { mods = {}, key = "XF86MonBrightnessDown", action = "spawn", args = {"brightnessctl", "s", "5%-"} },
}
